# Generated by Django 4.1.3 on 2023-06-13 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_alter_post_likes_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resized_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='post_user', through='posts.PostLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
