# Generated by Django 4.1.3 on 2023-06-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_access_token',
            field=models.CharField(blank=True, max_length=420, null=True, unique=True),
        ),
    ]
