# Generated by Django 4.1.3 on 2023-09-11 17:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_google_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 17, 7, 13, 830944, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=420),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=69, unique=True, validators=[django.core.validators.RegexValidator('^\\S+$', message='Usernames cannot contain spaces.')]),
        ),
    ]
