# Generated by Django 4.1.3 on 2023-09-13 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_username_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username_last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 22, 9, 4, 258091, tzinfo=datetime.timezone.utc)),
        ),
    ]
