# Generated by Django 4.1.3 on 2024-12-02 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_username_last_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username_last_updated",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 23, 24, 33, 536572, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
