# Generated by Django 4.1.3 on 2024-12-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poster_link", models.URLField(max_length=500)),
                ("series_title", models.CharField(max_length=255)),
                ("released_year", models.IntegerField()),
                ("certificate", models.CharField(blank=True, max_length=50, null=True)),
                ("runtime", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=255)),
                ("imdb_rating", models.FloatField()),
                ("overview", models.TextField(blank=True, null=True)),
                ("meta_score", models.IntegerField(blank=True, null=True)),
                ("director", models.CharField(max_length=255)),
                ("star1", models.CharField(max_length=255)),
                ("star2", models.CharField(max_length=255)),
                ("star3", models.CharField(max_length=255)),
                ("star4", models.CharField(max_length=255)),
                ("no_of_votes", models.IntegerField()),
                ("gross", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
